RMET-3770 ::: Android native library + bridges
ionic-team/outsystems-geolocation pull request #3
Opened 2024-12-27 17:04 UTC by OS-pedrogustavobilro

## Notes

This PR should only be merged (and reviewed?) after https://github.com/ionic-team/outsystems-geolocation/pull/1

Still missing:

- [ ] tests for Capacitor plugin
- [ ] Aligning on errors with iOS
- [ ] CI and Sonarqube

## Description

Add Geolocation native Android code to the `android-lib` package. Contains the Kotlin source files and unit tests.

Also contains the Android code for the cordova and capacitor plugins, which have the following changes, fixing some issues on behaviours on Android:

### Cordova changes

1. `getLocation` - renamed to `getCurrentPosition`
    - added usage of `maximumAge` in native Android code, used in `setMaxUpdateAgeMillis` (this one doesn't really make a huge difference as it is being used in Javascript as well).

2. `addWatch` - renamed to `watchPosition` 
    - `maximumAge` not used as `interval` anymore; used as maximum age actually with `setMaxUpdateAgeMillis`, and `timeout` is used as `interval`.

### Capacitor changes

1. `getCurrentPosition`
    - `timeout` is now used in retrieving the current location (i.e. if no location is retrieved until timeout, an error is returned.

2. `watchPosition`
    - the `timeout` parameter is no passed in the `interval` field (as opposed to `setMaxUpdateDelayMillis` which mostly just regulated batching), instead of being hardcoded 10 seconds.
    - added `maximumAge` through `setMaxUpdateAgeMillis`

3. `clearWatch`
    - fix: clearing one watch now does not remove location updates from the other watches.

## Type of changes

- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Refactor (cosmetic changes)
- [ ] Breaking change (change that would cause existing functionality to not work as expected)

## Platforms affected
- [x] Android
- [ ] iOS
- [ ] JavaScript

## Checklist

- [ ] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2025-01-02 10:16 UTC, OS-ricardomoreirasilva commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/controller/OSGLOCController.kt
> +            resolveLocationSettingsResultFlow.emit(
maybe we could emit the `resolveLocationSettingsResultFlow.emit(...)` duplication?

2025-01-02 10:16 UTC, OS-ricardomoreirasilva commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/controller/OSGLOCServiceHelper.kt
> +                )
Maybe we could avoid duplication of the `Result.failure(...)`.

2025-01-02 10:16 UTC, OS-ricardomoreirasilva commented on packages/capacitor-plugin/android/src/main/koltin/com/outsystems/capacitor/plugins/geolocation/GeolocationPlugin.kt
> +    }
Can we reuse the logic here? They differ only in the true statement.

2025-01-02 10:16 UTC, OS-ricardomoreirasilva commented on packages/capacitor-plugin/android/src/main/koltin/com/outsystems/capacitor/plugins/geolocation/GeolocationPlugin.kt
> +        }
This is pretty much identical to the `watchPosition`. Can't we reuse logic to avoid duplications?

2025-01-02 10:16 UTC, OS-ricardomoreirasilva commented on packages/cordova-plugin/src/web.ts
> +  exec(convertOnSuccess, error, 'OSGeolocation', 'watchPosition', [options, watchId]);
The `watchId` being passed here seems a bit lost when looking at the rest of the code (`clearWatch` only needs a single property and we're still encapsulating it into his structure). We should keep things consistent, either by creating a `WatchPositionOptions` structure or reusing `ClearWatchOptions` with a better naming.

2025-01-02 10:21 UTC, OS-ricardomoreirasilva commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/model/OSGLOCLocationOptions.kt
> +    val enableHighAccuracy: Boolean = true,
Should these values be set here? Aren't they OS-specific?

2025-01-02 10:28 UTC, alexgerardojacinto commented on packages/cordova-plugin/src/web.ts
> +  exec(convertOnSuccess, error, 'OSGeolocation', 'watchPosition', [options, watchId]);
This comment should probably be added to the PR with the JS code. It was included here for testing purposes but this is context of the other PR. With that said, I agree with you.

2025-01-02 10:54 UTC, OS-ricardomoreirasilva commented on packages/cordova-plugin/src/web.ts
> +  exec(convertOnSuccess, error, 'OSGeolocation', 'watchPosition', [options, watchId]);
I can fix it there then

2025-01-02 17:30 UTC, alexgerardojacinto commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/model/OSGLOCLocationOptions.kt
> +    val enableHighAccuracy: Boolean = true,
I believe they can be set. They should come defined from the OutSystems (Cordova) and Capacitor bridges, but if they're not, then this way we make sure the library has default values set.

2025-01-03 09:57 UTC, alexgerardojacinto commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/controller/OSGLOCController.kt
> +            resolveLocationSettingsResultFlow.emit(
Refactored, can you check?

2025-01-03 09:57 UTC, alexgerardojacinto commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/controller/OSGLOCServiceHelper.kt
> +                )
Refactored, can you check?

2025-01-03 09:57 UTC, alexgerardojacinto commented on packages/capacitor-plugin/android/src/main/koltin/com/outsystems/capacitor/plugins/geolocation/GeolocationPlugin.kt
> +    }
Refactored, can you check?

2025-01-03 09:57 UTC, alexgerardojacinto commented on packages/capacitor-plugin/android/src/main/koltin/com/outsystems/capacitor/plugins/geolocation/GeolocationPlugin.kt
> +        }
Refactored, can you check?

2025-01-03 10:25 UTC, OS-ricardomoreirasilva commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/model/OSGLOCLocationOptions.kt
> +    val enableHighAccuracy: Boolean = true,
The issue is that these values should be defined by the callers, not the library. Given the wide range of scenarios where this library might be used, location accuracy and response times are highly context-specific. Providing default values through an empty constructor could result in unpredictable behaviour and suboptimal outcomes in terms of precision, battery usage and CPU performance.
Additionally, relying on OS-provided defaults makes it look weird, especially for `enableHighAccuracy`, where both bridges use the setting oppositely.

2025-01-03 10:27 UTC, OS-ricardomoreirasilva commented on packages/capacitor-plugin/android/src/main/kotlin/com/outsystems/capacitor/plugins/geolocation/OSGeolocationErrors.kt
> +object OSGeolocationErrors {
Maybe we could remove the`OS` here and keep the same naming pattern as `GeolocationPlugin`.

2025-01-03 10:29 UTC, OS-ricardomoreirasilva commented on packages/cordova-plugin/android/OSGeolocationErrors.kt
> +    )
Should we split it by method?

2025-01-03 11:00 UTC, alexgerardojacinto commented on packages/cordova-plugin/android/OSGeolocationErrors.kt
> +    )
Not sure I understood what you meant. Do you mean having a specific "INVALID_INPUT" error for each method? Like one for `getCurrentPosition`, another for `watchPosition`, and so on?

2025-01-03 11:07 UTC, OS-ricardomoreirasilva commented on packages/cordova-plugin/android/OSGeolocationErrors.kt
> +    )
Yes, similar to what we did for InAppBrowser.

2025-01-03 12:18 UTC, alexgerardojacinto commented on packages/cordova-plugin/android/OSGeolocationErrors.kt
> +    )
Done, can you check?

2025-01-03 12:18 UTC, alexgerardojacinto commented on packages/capacitor-plugin/android/src/main/kotlin/com/outsystems/capacitor/plugins/geolocation/OSGeolocationErrors.kt
> +object OSGeolocationErrors {
Refactored, can you check?

2025-01-03 12:19 UTC, alexgerardojacinto commented on packages/android-lib/src/main/kotlin/com/outsystems/plugins/osgeolocation/model/OSGLOCLocationOptions.kt
> +    val enableHighAccuracy: Boolean = true,
That makes sense. I removed the default values, can you check?

2025-01-03 12:53 UTC, OS-ricardomoreirasilva approved these changes

2025-01-06 05:28 UTC, ItsChaceD requested changes

2025-01-06 05:28 UTC, ItsChaceD commented on packages/capacitor-plugin/android/src/main/kotlin/com/outsystems/capacitor/plugins/geolocation/GeolocationPlugin.kt
> +        super.handleOnDestroy()
Maybe also clear `watchingCalls` to prevent memory leaks?

2025-01-06 05:28 UTC, ItsChaceD commented on packages/cordova-plugin/src/web.ts
> +        altitudeAccuracy: position.accuracy
Should this be `position.altitudeAccuracy`?

2025-01-06 09:43 UTC, alexgerardojacinto commented on packages/capacitor-plugin/android/src/main/kotlin/com/outsystems/capacitor/plugins/geolocation/GeolocationPlugin.kt
> +        super.handleOnDestroy()
I believe that isn't necessary, as the Android system will automatically take care of clearing the map when the app is closed

2025-01-06 10:01 UTC, alexgerardojacinto commented on packages/cordova-plugin/src/web.ts
> +        altitudeAccuracy: position.accuracy
Yes, nice catch! Fixed! Can you check?

2025-01-06 11:51 UTC, OS-ricardomoreirasilva approved these changes

2025-01-06 17:44 UTC, ItsChaceD approved these changes

2025-01-06 17:57 UTC, merged